### ISSUE TITLE
Not usable anymore

### ISSUE THREAD

**Issue by MG-ng** [techexpertize/SignApk#1]
Hey,

I did a tutorial that used your repository in one step. But an error occurred: 

`Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
        at com.android.signapk.SignApk.addDigestsToManifest(SignApk.java:169)
        at com.android.signapk.SignApk.main(SignApk.java:325)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)`

I read somewhere that this error is caused by using outdated libraries, and since you did not attach the .java files to the repo, I am not sure and cannot fix it. 

I think that it this tool worked quite well with the old java versions. It's just unfortunate that this and all the forks are not compatible with the newer java versions (I didn't check the exact version).

**Comment by simpleperson123** [comment]
Same for me (i have the newest JRE/JDK). And yes, its caused by deprecated libraries. Hopefully, it should be possible to rewrite this tool to support new Java versions.

**Comment by dkgitdev** [comment]
I've just used this after installing jdk8 from chocolaty repositories.

**Comment by oysteins-a** [comment]
> I've just used this after installing jdk8 from chocolaty repositories.

This worked for me. Remember to first uninstall other JDK versions before installing jdk8 with chocolatey.

**Comment by apixandru** [comment]
If anyone's interested, I decompiled the signapk jar and repackaged it to be java9+ compatible 

https://github.com/apixandru/signapk/releases
